export const REQUESTED_SERVICES: string[] = [
    'Street Light Repair',
    'Pothole Repair',
    'Garbage Collection Request',
    'Tree Trimming Or Removal',
    'Sidewalk Repair',
    'Water Leakage Report',
    'Sewer Maintenance',
    'Power Outage Report',
    'Internet Cable Service Issue',
    'Gas Line Inspection',
    'New Resident Registration',
    'Parking Permit Application',
    'Noise Complaint Mediation',
    'Building Permit Request',
    'Public Records Access',
    'Schedule Appointment With City Official',
    'Request For Social Services',
    'Report Lost And Found Item',
    'Public Transportation Schedule Inquiry',
    'Community Center Room Booking'
];
