spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/public_works_management
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: contracts
        initialize-schema: true


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

qdrant:
  url: http://localhost:6333

minio:
  endpoint: http://localhost:9100
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: case-photos

custom:
  ai:
    prompt:
      request-case: |
        Tu esi išmaniojo miesto paslaugų sistemos pagalbininkas.
        
        Naudotojas pateikė šią užklausą:
        
        %s
        
        Remdamasis pateikta informacija, sugeneruok iki 3 trumpų ir aiškių patikslinančių klausimų,
        kurie padėtų geriau suprasti naudotojo poreikius.
        Užduok tik aktualius ir naudotojui suprantamus klausimus.

      supplier-suggestions: |
        Tu esi Lietuvos viešųjų pirkimų pagalbininkas.

        Naudok TIK žemiau pateiktus tiekėjus.
        NESUKURK naujų tiekėjų.

        Surikiuok tiekėjus pagal jų tinkamumą šiai užklausai.

        Vertinant naudok:

        - CPV kodų atitikimą
        - ankstesnių projektų panašumą
        - pirkėjų tipą
        - veiklos srities sutapimą

        Grąžink TIK galiojantį JSON be papildomo teksto.

        JSON struktūra:

        [
          {
            "name": "...",
            "reason": "...",
            "confidence": 0.0
          }
        ]

        Galimi tiekėjai ir jų ankstesni projektai:

        %s

        Viešojo pirkimo užklausa:

        %s

      document-retrieval-request: |
        Viešojo pirkimo užklausa:
        
        Pavadinimas:
          %s
        
        Aprašymas:
          %s
        
        Pasiūlyk tiekėjus, galinčius suteikti šią paslaugą.